---
- name: Add replica user
  become: true
  become_user: postgres
  community.postgresql.postgresql_user:
    name: "{{ replica_user_name }}"
    password: "{{ replica_user_password }}"
    role_attr_flags: replication

# trust connection to avoid inserting password
- name: Grant replica access
  become: true
  community.postgresql.postgresql_pg_hba:
    dest: "{{ postgresql_conf_dir }}/pg_hba.conf"
    contype: host
    users: "{{ replica_user_name }}"
    source: "{{ replica_ip }}/24"
    databases: replication
    method: trust
  notify: Restart PostgreSQL

- name: Set config options
  template:
    src: ansible_master.conf.j2
    dest: "{{ postgresql_conf_dir }}/conf.d/ansible_master.conf"
    owner: "{{ postgresql_user_name }}"
    group: "{{ postgresql_user_name }}"
    mode: 0644
    backup: true
  notify: Reload PostgreSQL
