---
# PostgreSQL must be stopped and the data dir must be empty before replication
- name: Stop PostgreSQL
  service:
    name: "{{ postgresql_service_name }}"
    state: stopped

- name: Check if replica exists
  stat:
    path: "{{ replica_data_path }}/standby.signal"
  register: replica_signal

- name: Clear out data directory
  file:
    path: "{{ replica_data_path }}"
    state: absent
  when: not replica_signal.stat.exists

- name: Create empty data directory
  file:
    path: "{{ replica_data_path }}"
    state: directory
    owner: postgres
    group: postgres
    mode: "0700"
  when: not replica_signal.stat.exists

- name: Create base backup
  become: true
  become_user: postgres
  command:
    cmd: pg_basebackup -D {{ replica_data_path }} -h {{ master_ip }} -U {{ replica_user_name }} -P -R -X stream
  when: not replica_signal.stat.exists

- name: Set config options
  template:
    src: ansible_replica.conf.j2
    dest: "{{ postgresql_conf_dir }}/conf.d/ansible_replica.conf"
    owner: "{{ postgresql_user_name }}"
    group: "{{ postgresql_user_name }}"
    mode: 0644
    backup: true
  notify: Reload PostgreSQL

- name: Start and enable PostgreSQL
  service:
    name: "{{ postgresql_service_name }}"
    state: started
    enabled: yes
